In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
ds=pd.read_csv("Self_Awareness_Dataset.csv")

In [3]:
ds

Date       Day  Sleep Hour  Exercise Hour  Study Hour  StudyDS Hour  \
0   14-Jan    Friday        10.0            1.0         3.0           0.0   
1   15-Jan  Saturday        11.0            2.0         4.0           0.0   
2   16-Jan    Sunday         7.0            0.0         3.0           2.0   
3   17-Jan    Monday         6.0            1.0         2.0           2.0   
4   18-Jan   Tuesday         8.0            3.0         4.0           1.0   
..     ...       ...         ...            ...         ...           ...   
64     NaN       NaN         NaN            NaN         NaN           NaN   
65     NaN       NaN         NaN            NaN         NaN           NaN   
66     NaN       NaN         NaN            NaN         NaN           NaN   
67     NaN       NaN         NaN            NaN         NaN           NaN   
68     NaN       NaN         NaN            NaN         NaN           NaN   

    Work Hour  End of the day Feeling (0 to 10)  Total Hours  Unnamed: 9  \
0         4.0                               3.0         21.0         NaN   
1         6.0                               4.0         27.0         NaN   
2         2.0                               5.0         19.0         NaN   
3         5.0                               2.0         18.0         NaN   
4         3.0                               4.0         23.0         NaN   
..        ...                               ...          ...         ...   
64        NaN                               NaN          NaN         NaN   
65        NaN                               NaN          NaN         NaN   
66        NaN                               NaN          NaN         NaN   
67        NaN                               NaN          NaN         NaN   
68        NaN                               NaN          NaN         NaN   

    Unnamed: 10  Unnamed: 11  \
0           NaN          NaN   
1           NaN          NaN   
2           NaN          NaN   
3           NaN          NaN   
4           NaN          NaN   
..          ...          ...   
64          NaN          NaN   
65          NaN          NaN   
66          NaN          NaN   
67          NaN          NaN   
68          NaN          NaN   

                                          Unnamed: 12  
0                                                 NaN  
1                                                 NaN  
2                                                 NaN  
3   Feeling: 0 (�not at all�) to 10 (�extremely�) ...  
4                                                 NaN  
..                                                ...  
64                                                NaN  
65                                                NaN  
66                                                NaN  
67                                                NaN  
68                                                NaN  

[69 rows x 13 columns]

In [4]:
ds=ds.drop(['Unnamed: 9'], axis=1)
ds=ds.drop(['Unnamed: 10'], axis=1)
ds=ds.drop(['Unnamed: 11'], axis=1)
ds=ds.drop(['Unnamed: 12'], axis=1)

In [5]:
ds=ds.drop([68],axis=0)
ds=ds.drop([67],axis=0)
ds=ds.drop([66],axis=0)
ds=ds.drop([65],axis=0)
ds=ds.drop([64],axis=0)

In [6]:
ds

Date        Day  Sleep Hour  Exercise Hour  Study Hour  StudyDS Hour  \
0   14-Jan     Friday        10.0           1.00         3.0           0.0   
1   15-Jan   Saturday        11.0           2.00         4.0           0.0   
2   16-Jan     Sunday         7.0           0.00         3.0           2.0   
3   17-Jan     Monday         6.0           1.00         2.0           2.0   
4   18-Jan    Tuesday         8.0           3.00         4.0           1.0   
..     ...        ...         ...            ...         ...           ...   
59  14-Mar     Monday         6.0           0.25         2.0           0.0   
60  15-Mar    Tuesday         4.0           0.25         3.0           0.0   
61  16-Mar  Wednesday         4.0           0.20         2.0           0.0   
62  17-Mar   Thursday         5.0           0.10         3.0           2.0   
63  18-Mar     Friday        12.0           0.80         4.0           2.0   

    Work Hour  End of the day Feeling (0 to 10)  Total Hours  
0         4.0                               3.0        21.00  
1         6.0                               4.0        27.00  
2         2.0                               5.0        19.00  
3         5.0                               2.0        18.00  
4         3.0                               4.0        23.00  
..        ...                               ...          ...  
59        5.0                               3.0        16.25  
60        3.0                               7.0        17.25  
61        5.0                               9.0        20.20  
62        2.0                               9.0        21.10  
63        5.0                               8.0        31.80  

[64 rows x 9 columns]

In [7]:
ds.isnull().sum()

Date                                0
Day                                 0
Sleep Hour                          0
Exercise Hour                       0
Study Hour                          0
StudyDS Hour                        0
Work Hour                           0
End of the day Feeling (0 to 10)    0
Total Hours                         0
dtype: int64

In [9]:
ds.columns

Index(['Date', 'Day', 'Sleep Hour', 'Exercise Hour', 'Study Hour',
       'StudyDS Hour', 'Work Hour', 'End of the day Feeling (0 to 10)',
       'Total Hours'],
      dtype='object')

In [11]:
X=ds[['Sleep Hour', 'Exercise Hour', 'Study Hour','StudyDS Hour', 'Work Hour']]
y=ds[['End of the day Feeling (0 to 10)']]

In [18]:
X = pd.get_dummies(ds[['Sleep Hour', 'Exercise Hour', 'Study Hour','StudyDS Hour', 'Work Hour','Day']], drop_first=False)
X.head(6)

Sleep Hour  Exercise Hour  Study Hour  StudyDS Hour  Work Hour  Day_Friday  \
0        10.0            1.0         3.0           0.0        4.0           1   
1        11.0            2.0         4.0           0.0        6.0           0   
2         7.0            0.0         3.0           2.0        2.0           0   
3         6.0            1.0         2.0           2.0        5.0           0   
4         8.0            3.0         4.0           1.0        3.0           0   
5         7.0            1.0         3.0           0.0        5.0           0   

   Day_Monday  Day_Saturday  Day_Sunday  Day_Thursday  Day_Tuesday  \
0           0             0           0             0            0   
1           0             1           0             0            0   
2           0             0           1             0            0   
3           1             0           0             0            0   
4           0             0           0             0            1   
5           0             0           0             0            0   

   Day_Wednesday  
0              0  
1              0  
2              0  
3              0  
4              0  
5              1

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=.2,random_state=0)

In [20]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression()

In [28]:
X.head(10)

Sleep Hour  Exercise Hour  Study Hour  StudyDS Hour  Work Hour  Day_Friday  \
0        10.0            1.0         3.0           0.0        4.0           1   
1        11.0            2.0         4.0           0.0        6.0           0   
2         7.0            0.0         3.0           2.0        2.0           0   
3         6.0            1.0         2.0           2.0        5.0           0   
4         8.0            3.0         4.0           1.0        3.0           0   
5         7.0            1.0         3.0           0.0        5.0           0   
6         4.0            0.0         4.0           2.0        2.0           0   
7        12.0            0.0         3.0           0.0        4.0           1   
8        11.0            0.0         3.0           0.0        6.0           0   
9         5.0            1.0         2.0           2.0        2.0           0   

   Day_Monday  Day_Saturday  Day_Sunday  Day_Thursday  Day_Tuesday  \
0           0             0           0             0            0   
1           0             1           0             0            0   
2           0             0           1             0            0   
3           1             0           0             0            0   
4           0             0           0             0            1   
5           0             0           0             0            0   
6           0             0           0             1            0   
7           0             0           0             0            0   
8           0             1           0             0            0   
9           0             0           1             0            0   

   Day_Wednesday  
0              0  
1              0  
2              0  
3              0  
4              0  
5              1  
6              0  
7              0  
8              0  
9              0

In [25]:
y.head()

End of the day Feeling (0 to 10)
0                               3.0
1                               4.0
2                               5.0
3                               2.0
4                               4.0

In [26]:
y_pred=regressor.predict(X_test)

Test 1: The real value was 6

In [29]:
regressor.predict([[8,0.25,3,0,2,0,0,0,0,1,0,0]])

array([[5.33292274]])

Test 2: The real value was 4

In [30]:
regressor.predict([[7,0.25,1,1,3,0,0,0,0,0,1,0]])

array([[5.96517297]])

Test 3: The real value was 5

In [31]:
regressor.predict([[6,0.2,2,0,5,0,1,0,0,0,0,0]])

array([[5.55737235]])

Test 4: The real value was 6


In [34]:
regressor.predict([[12,0.2,4,0,4,1,0,0,0,0,0,0]])

array([[5.00118245]])

Test 5: The real value was 9


In [35]:
regressor.predict([[5,0.1,3,2,2,0,0,0,0,1,0,0]])

array([[4.87038872]])

In [36]:
print("Coefficients",regressor.coef_)

Coefficients [[-0.07985077 -0.71603034  0.17079297 -0.40474544  4.23792664 -1.40944154
  -5.22869698 -8.88753945  7.73662013  7.28534343  4.34614762 -3.84243321]]


In [37]:
print("intercept",regressor.intercept_)

intercept [-10.12283911]


In [38]:
from sklearn.metrics import r2_score
print("r2-score",r2_score(y_test,y_pred))

r2-score -0.30737572122440593


In [39]:
import statsmodels.api as sm
X=sm.add_constant(X)

In [40]:
model=sm.OLS(y,X).fit()

In [41]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                   OLS Regression Results                                   
============================================================================================
Dep. Variable:     End of the day Feeling (0 to 10)   R-squared:                       0.219
Model:                                          OLS   Adj. R-squared:                  0.054
Method:                               Least Squares   F-statistic:                     1.329
Date:                              Tue, 22 Mar 2022   Prob (F-statistic):              0.236
Time:                                      09:39:16   Log-Likelihood:                -121.18
No. Observations:                                64   AIC:                             266.4
Df Residuals:                                    52   BIC:                             292.3
Df Model:                                        11                                         
Covariance Type:                          nonrobust                                         
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const            -8.1022      6.558     -1.236      0.222     -21.261       5.057
Sleep Hour       -0.1439      0.154     -0.935      0.354      -0.453       0.165
Exercise Hour    -0.7982      0.459     -1.738      0.088      -1.720       0.123
Study Hour        0.0839      0.251      0.334      0.740      -0.420       0.588
StudyDS Hour     -0.1917      0.310     -0.618      0.540      -0.815       0.431
Work Hour         4.2148      2.021      2.085      0.042       0.159       8.270
Day_Friday       -2.5594      1.480     -1.729      0.090      -5.530       0.411
Day_Monday       -6.1709      3.274     -1.885      0.065     -12.740       0.398
Day_Saturday     -9.7039      5.209     -1.863      0.068     -20.156       0.748
Day_Sunday        6.1651      2.902      2.124      0.038       0.341      11.989
Day_Thursday      6.2366      2.897      2.153      0.036       0.423      12.050
Day_Tuesday       2.8150      1.010      2.788      0.007       0.789       4.841
Day_Wednesday    -4.8846      3.335     -1.465      0.149     -11.576       1.807
==============================================================================
Omnibus:                        0.108   Durbin-Watson:                   1.848
Prob(Omnibus):                  0.947   Jarque-Bera (JB):                0.243
Skew:                          -0.086   Prob(JB):                        0.885
Kurtosis:                       2.752   Cond. No.                     8.47e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 7.88e-31. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""